/* ============================================================
   MODELO DE DADOS — Livro de Técnicas e Receitas
   Todo o conteúdo vem dos documentos do projeto "Receitas".
   ============================================================ */

const LIVRO = {
  titulo: "Fogo Baixo",
  subtitulo: "Um livro de técnicas e receitas",
  autor: "Celso Zanchetta",
  edicao: "Edição de julho de 2026",
};

const UNIDADES = { caseiro: "Caseiro", peso: "Gramas" };

const CAPITULOS = [
  { id: "frango", nome: "Frango" },
  { id: "carnes", nome: "Carnes na chapa e no forno" },
  { id: "feijoada", nome: "Um dia inteiro: a feijoada" },
  { id: "arroz", nome: "Arroz e massas rápidas" },
  { id: "conservas", nome: "Conservas e fermentados" },
  { id: "beber", nome: "Para beber" },
];

/* ============================================================
   TÉCNICAS
   ============================================================ */
const TECNICAS = [
  {
    id: "principio-pele",
    titulo: "O princípio da pele crocante",
    kicker: "TÉCNICA · VALE PARA TODA AVE COM PELE",
    resumo:
      "Frigideira fria, fogo baixo e paciência produzem pele vidrada. Pressa produz borracha.",
    corpo: [
      {
        h: "A gordura precisa sair antes de a superfície dourar",
        p: "Sob a pele existe uma camada de gordura. Se a superfície doura antes de essa gordura derreter, ela fica presa: a pele endurece por fora e continua flácida por baixo. Começar com a frigideira fria e subir o calor devagar dá tempo para a gordura render e escapar — a pele então frita na própria gordura e vitrifica.",
      },
      {
        h: "Água é a inimiga",
        p: "Enquanto houver umidade na superfície, a pele não passa de 100 °C, e nada doura a 100 °C: toda a energia do fogo vai para evaporar água em vez de tostar. Secar com papel toalha não é capricho, é a etapa que mais muda o resultado. Frango que ficou marinando precisa de cuidado dobrado — o tempero deixa a pele encharcada.",
      },
      {
        h: "Contato total",
        p: "A pele encolhe e empena ao esquentar, e o meio dela deixa de tocar a frigideira. Um peso por cima — outra panela, uma leiteira com água — mantém a superfície inteira em contato com o metal. Sem peso, o resultado é uma coroa dourada com um centro pálido.",
      },
      {
        h: "Não cutuque",
        p: "Cada vez que a peça é levantada, o vapor entra por baixo e amolece o que já estava crocante. Doze a quinze minutos sem tocar parece muito tempo na primeira vez. É o tempo certo.",
      },
      {
        h: "Açúcar queima antes",
        p: "Mel, shoyu e molho barbecue caramelizam bem antes de a pele terminar. Para este método, tempero seco: sal, ervas, pimenta, páprica, alho. Doce entra depois, no prato, se entrar.",
      },
    ],
    notas: [
      "Ponto certo: 75 °C no centro, ou o osso soltando fácil da carne.",
      "Frango cru temperado dura 1–2 dias na geladeira. No segundo dia, cheire e toque antes: cheiro neutro e superfície não pegajosa = ok, mas cozinhe naquele dia.",
      "Marinada líquida atrapalha. Se usar, escorra e seque bem antes de levar ao fogo.",
    ],
  },

  {
    id: "disciplina-do-sal",
    titulo: "A disciplina do sal",
    kicker: "TÉCNICA · A REGRA QUE ATRAVESSA O LIVRO INTEIRO",
    resumo:
      "Quase toda receita daqui tem três ou quatro fontes de sódio escondidas. Prove antes, sempre.",
    corpo: [
      {
        h: "O sal quase nunca vem só do saleiro",
        p: "Olhe o padrão. A feijoada tem carne seca, costela salgada, orelha, rabo, paio e calabresa — seis fontes antes de qualquer pitada. O fried rice tem bacon, calabresa, shoyu e aji-no-moto. O risone tem tablete de caldo, hondashi e lemon pepper. A marinada da fraldinha tem shoyu, molho inglês, nam pla e sal. Os medalhões têm shoyu no molho. O escabeche tem o peixe e o banho de vinagre já salgados. Em todos esses casos, salgar no começo é apostar às cegas.",
      },
      {
        h: "A regra prática",
        p: "Sal entra no fim, depois de provar — e frequentemente não entra. Nas receitas com redução (o molho dos medalhões, a redução da marinada da fraldinha), lembre que concentrar o líquido concentra o sal junto: um molho equilibrado no meio da redução fica salgado no fim.",
      },
      {
        h: "As exceções são poucas e claras",
        p: "Carne que vai selar leva sal generoso na superfície, só na hora de ir para a chapa — ali o sal faz crosta, não tempero interno. Batata cozida leva sal na água, porque é a única chance de temperar por dentro; depois, sal leve por cima. Salada leva sal só na hora de servir, senão vira sopa. Vinagrete, idem.",
      },
      {
        h: "Quando o sal já foi longe demais",
        p: "Nas carnes salgadas, o controle é a dessalga: 24 horas na geladeira em bastante água, trocando a cada 3 a 4 horas. Se o tempo foi menor, prove um pedacinho cru antes de cozinhar — se ainda estiver salgado, pré-cozinhe 15 minutos em vez de 10 e troque a água no meio.",
      },
    ],
    notas: [
      "Prove o líquido da marinada antes de reaproveitá-lo como molho.",
      "Se o molho leva shoyu, alivie o sal de tudo o que vai junto no prato — carne e acompanhamentos.",
      "Salgar no fim é corrigível. Salgar no começo, não.",
    ],
  },

  {
    id: "ponto-sem-termometro",
    titulo: "Ponto de carne sem termômetro",
    kicker: "TÉCNICA · CUT-AND-PEEK, DESCANSO E O CENTRO FRIO",
    resumo:
      "Três hábitos resolvem o ponto sem instrumento: tirar da geladeira antes, olhar por dentro, e descansar.",
    corpo: [
      {
        h: "O centro frio é o maior inimigo",
        p: "Carne que sai da geladeira direto para o fogo cozinha de fora para dentro com uma diferença enorme entre superfície e miolo — quando o centro chega ao ponto, a borda já passou. Peça fina de chapa: 20 a 30 minutos fora da geladeira. Peça alta: 30 a 40 minutos. Fraldinha inteira para o forno: uma hora cheia. Não é frescura; é o que torna o tempo previsível.",
      },
      {
        h: "Cut-and-peek",
        p: "Sem termômetro, o método é olhar. Faça um corte pequeno no ponto mais grosso e leia a cor: vermelho frio no centro significa que falta; rosa quente é mal para ao ponto; levemente rosado, quase sem rosa e ainda úmido é o ponto+ — que costuma agradar mais em peça servida quente; cinza por igual é bem passado, e daí não volta. O corte perde alguns sucos e não tem importância nenhuma perto do prejuízo de errar o ponto.",
      },
      {
        h: "Seco doura, úmido cozinha no vapor",
        p: "O mesmo princípio da pele do frango vale para toda carne selada. Papel toalha na superfície antes de qualquer coisa — especialmente depois de marinada, que encharca. Panela de fundo fino e carne úmida é a combinação que faz a peça soltar água e cozinhar em vez de dourar.",
      },
      {
        h: "O descanso não é opcional",
        p: "Cinco minutos para peça fina, oito a dez para peça alta ou para uma fraldinha inteira. É nesse tempo que os sucos redistribuem. Fatiar antes disso esvazia a tábua e resseca a carne — e, no caso da fraldinha, o corte fino contra as fibras vale mais para a maciez do que qualquer outra coisa que você faça na receita.",
      },
      {
        h: "O que não reaquece",
        p: "Carne servida ao ponto não volta ao fogo: fraldinha ao ponto requentada vira borracha. Se não dá para servir na hora, mude de método — braseado a 150–160 °C por 2h30 a 3h com líquido cobrindo reaquece perfeitamente. Rosbife frio é o outro caminho válido: asse até o ponto, refrigere, fatie fino e sirva em temperatura ambiente. Nunca reaqueça.",
      },
    ],
    notas: [
      "Referência de termômetro, quando houver: ~63 °C para suíno rosado, com o descanso; 75 °C para frango.",
      "Pimenta-do-reino queima na chapa: entra depois de selar.",
      "Sal generoso na superfície só na hora de ir para o fogo.",
    ],
  },

  {
    id: "chapa-e-fogo",
    titulo: "Chapa, panela e a boca de 4,5 kW",
    kicker: "TÉCNICA · REGULE PELO QUE VOCÊ VÊ, NÃO PELO REGISTRO",
    resumo:
      "Fogo forte demais é o erro mais comum de quem tem uma boca turbo. Escolha da panela e calor de recuperação valem mais que potência.",
    corpo: [
      {
        h: "Calor de recuperação",
        p: "O que importa quando a carne fria toca o metal não é a temperatura máxima, é o quanto a superfície aguenta sem despencar. Chapa removível sobre a boca alta, ferro fundido e inox de fundo grosso seguram calor e formam um fond bonito. Alumínio de fundo fino serve, mas perde temperatura na hora: contorne pré-aquecendo bem e selando em lotes pequenos, deixando a panela recuperar entre um lote e outro.",
      },
      {
        h: "Regule pelo que você vê",
        p: "Numa boca de 4,5 kW, 'médio' é bem menos chama do que parece. Olhe o borbulhar do risone, o chiado da carne, a cor do alho — não a posição do registro. A panela esquenta muito e segura calor: dê o comando e espere ela responder, em vez de ir no máximo e correr atrás do estrago.",
      },
      {
        h: "O alho queima em segundos",
        p: "Aparece em quase toda receita deste livro e é a coisa que mais estraga um refogado. Fogo médio-baixo, e tire do fogo antes do que parece necessário — a panela quente continua cozinhando depois que você desliga. Alho escuro amarga o prato inteiro.",
      },
      {
        h: "Pré-aqueça e teste",
        p: "Chapa: 5 a 8 minutos em registro baixo-médio para o calor espalhar. A chama concentra no centro, então sele no centro mesmo. O teste é a gota d'água — ela deve dançar e sumir em 1 a 2 segundos. Some instantaneamente: ainda não está quente o bastante para o modo Leidenfrost. Fica parada fervendo: falta muito.",
      },
      {
        h: "Antiaderente não faz molho",
        p: "Quase não forma fond, e o revestimento degrada em fogo alto. Se o molho vem do fundo da panela — e neste livro vem, quase sempre —, use inox ou ferro.",
      },
    ],
    notas: [
      "Fond que gruda no fundo não é erro, é sabor. Deglaceie com água, cachaça, cerveja ou shoyu e raspe.",
      "Panela larga e baixa evapora e absorve por igual; panela funda e estreita empilha e abafa.",
      "Álcool em panela muito quente pode inflamar: tire do fogo antes de acrescentar cachaça ou vinho.",
    ],
  },

  {
    id: "fermentacao-segura",
    titulo: "Fermentar em salmoura sem medo",
    kicker: "TÉCNICA · SAL A 3%, TUDO SUBMERSO, O NARIZ DECIDE",
    resumo:
      "Lacto-fermentação é simples e segura quando três regras são obedecidas. A quarta regra é saber quando descartar.",
    corpo: [
      {
        h: "Como funciona",
        p: "Legumes submersos em salmoura fermentam pela ação de bactérias láticas, que acidificam o meio e protegem contra tudo o que estraga. O sal e o ácido fazem a conservação; o tempo só aprofunda o sabor, deixando mais azedo e mais redondo. Por isso o prazo é flexível: uma semana dá um resultado fresco, alguns meses dão um resultado complexo, e nenhum dos dois é mais seguro que o outro.",
      },
      {
        h: "Sal a 3% do peso total",
        p: "Três por cento do peso de vegetal mais água, não só da água. Pese o conjunto no pote e calcule daí. Sal comum funciona: o iodo, na quantidade que existe no sal de mesa, não atrapalha as bactérias — no máximo deixa a salmoura um pouco turva.",
      },
      {
        h: "Tudo submerso",
        p: "É acima da linha do líquido que mofa. Um saquinho limpo cheio de salmoura a 3% — não de água pura, para o caso de vazar — enfiado no gargalo faz peso e isola do ar. Tampa frouxa: a fermentação solta CO₂ e pote cheio transborda nos primeiros dias. Deixe num pratinho, longe do sol. Vai turvar e borbulhar: é o certo.",
      },
      {
        h: "Kahm ou mofo",
        p: "Película branca lisa na superfície é kahm, uma levedura inofensiva — retire com a colher e siga. Qualquer coisa felpuda ou peluda, de qualquer cor, é mofo: descarte o lote inteiro, sem tentar raspar para salvar. O cheiro tem que ser azedo e agradável, tipo picles; pútrido significa descarte. Fita de pH abaixo de 4 confirma que está seguro.",
      },
    ],
    notas: [
      "Comece a provar do quinto ao sétimo dia. O ponto é o gosto, não o calendário.",
      "Processador só no fim. A versão mash — purê fermentado, sal sobre o peso da pasta, sem água — é outro método, que fermenta mais rápido e seca no topo se descuidar.",
      "Fermentar não tira ardência, só arredonda. Calibre o calor provando o blend cru: dá para subir, não para descer.",
    ],
  },
];

/* ============================================================
   RECEITAS
   ============================================================ */
const RECEITAS = [
  /* ===================== FRANGO ===================== */
  {
    id: "sobrecoxa-frigideira",
    capitulo: "frango",
    titulo: "Sobrecoxa na frigideira",
    kicker: "UMA FRIGIDEIRA · SEM MOLHO · O MELHOR RESULTADO",
    subtitulo: "Pele vidrada, carne suculenta, arrematada na manteiga com alho e ervas.",
    porcoes: 2, porcoesOpcoes: [2, 4, 6], ativo: 30, total: 55,
    utensilio: "Frigideira de fundo grosso",
    faixa: "SEQUE MUITO BEM A PELE ANTES DE COMEÇAR",
    ingredientes: [
      { q: 4, u: "un", alt: { q: 720, u: "g" }, nome: "sobrecoxas com pele e osso", obs: "~180 g cada" },
      { q: 1, u: "col. chá", alt: { q: 6, u: "g" }, nome: "sal", obs: "grosso, moído na hora" },
      { q: 1, u: "col. chá", alt: { q: 1, u: "g" }, nome: "ervas secas", obs: "tomilho, alecrim ou orégano" },
      { q: 0.5, u: "col. chá", alt: { q: 1, u: "g" }, nome: "pimenta-do-reino", obs: "moída na hora" },
      { q: 1, u: "col. sopa", alt: { q: 15, u: "ml" }, nome: "azeite ou óleo neutro", obs: "só para cobrir o fundo" },
      { q: 1, u: "col. sopa", alt: { q: 15, u: "g" }, nome: "manteiga", obs: "para arrematar" },
      { q: 2, u: "dentes", alt: { q: 10, u: "g" }, nome: "alho", obs: "amassados, com casca" },
      { q: 2, u: "ramos", alt: { q: 4, u: "g" }, nome: "alecrim ou tomilho frescos", obs: "opcional" },
    ],
    grade: [
      { col: 1, de: 0, ate: 3, titulo: "temperar e secar", detalhe: "20 min fora da geladeira · papel toalha" },
      { col: 2, de: 0, ate: 4, titulo: "frigideira fria, pele para baixo", detalhe: "só então ligue o fogo médio-baixo" },
      { col: 3, de: 0, ate: 4, titulo: "dourar sem mexer", detalhe: "12–15 min · com peso por cima" },
      { col: 4, de: 0, ate: 4, titulo: "virar", detalhe: "5–6 min do lado da carne" },
      { col: 5, de: 0, ate: 7, titulo: "arrematar na manteiga", detalhe: "1 min · regando com a colher" },
      { col: 6, de: 0, ate: 7, titulo: "descansar", detalhe: "5 min · 75 °C no centro" },
    ],
    modo: [
      { t: "Tire o frango da geladeira 20 minutos antes. Tempere com o sal, as ervas secas e a pimenta." },
      { t: "Seque muito bem a pele com papel toalha. Se o frango ficou marinando, esse passo é obrigatório — o tempero deixa a pele encharcada." },
      { t: "Na frigideira fria, ponha um fio de óleo, só para cobrir o fundo. Acomode as sobrecoxas com a pele para baixo e só então ligue o fogo médio-baixo." },
      { t: "Doure 12 a 15 minutos sem mexer e sem cutucar. Ponha um peso por cima — outra panela, uma leiteira com água — para garantir contato total da pele com a frigideira.", timer: 780 },
      { t: "Vire as peças. Mais 5 a 6 minutos do lado da carne.", timer: 330 },
      { t: "Junte a manteiga, o alho amassado e os ramos de alecrim ou tomilho. Incline a panela e regue a carne com a manteiga espumante por 1 minuto.", timer: 60 },
      { t: "Descanse 5 minutos antes de servir. Ponto: 75 °C no centro, ou o osso soltando fácil da carne.", timer: 300 },
    ],
    notas: [
      "A gordura que sobrou na frigideira é ingrediente, não sujeira: vale para as batatas ou para o arroz de alho.",
      "Evite temperos com açúcar (mel, shoyu, barbecue) — queimam antes de a pele ficar pronta.",
      "Sem peso por cima, a pele empena e doura só nas bordas.",
    ],
  },
  {
    id: "sobrecoxa-airfryer",
    capitulo: "frango",
    titulo: "Sobrecoxa na airfryer",
    kicker: "SEM VIGIAR · SEM SUJEIRA · O MAIS PRÁTICO",
    subtitulo: "Quase tão bom quanto a frigideira, com um décimo do trabalho. Não precisa virar.",
    porcoes: 2, porcoesOpcoes: [2, 4, 6], ativo: 5, total: 30,
    utensilio: "Airfryer",
    faixa: "PELE PARA CIMA · NÃO LOTE O CESTO",
    ingredientes: [
      { q: 4, u: "un", alt: { q: 720, u: "g" }, nome: "sobrecoxas com pele e osso" },
      { q: 1, u: "col. chá", alt: { q: 6, u: "g" }, nome: "sal" },
      { q: 1, u: "col. chá", alt: { q: 1, u: "g" }, nome: "ervas secas", obs: "ou lemon pepper, ou páprica" },
      { q: 0.5, u: "col. chá", alt: { q: 1, u: "g" }, nome: "pimenta-do-reino", obs: "moída na hora" },
      { q: 1, u: "col. chá", alt: { q: 5, u: "ml" }, nome: "azeite", obs: "opcional, um fio" },
    ],
    grade: [
      { col: 1, de: 0, ate: 3, titulo: "temperar e secar", detalhe: "papel toalha na pele" },
      { col: 2, de: 0, ate: 4, titulo: "no cesto, pele para cima", detalhe: "sem encostar uma peça na outra" },
      { col: 3, de: 0, ate: 4, titulo: "assar 180 °C", detalhe: "25 min · sem virar" },
      { col: 4, de: 0, ate: 4, titulo: "descansar", detalhe: "5 min" },
    ],
    modo: [
      { t: "Tempere as sobrecoxas com sal, ervas e pimenta. Seque bem a pele com papel toalha." },
      { t: "Arrume no cesto com a pele para cima, sem encostar uma peça na outra — se lotar, o ar não circula e a pele cozinha no vapor." },
      { t: "Airfryer a 180 °C por 25 minutos. Não vire, não abra.", timer: 1500 },
      { t: "Descanse 5 minutos. Fica muito bom, só um pouco menos vidrado que a frigideira.", timer: 300 },
    ],
    notas: [
      "Se a airfryer for pequena, faça duas fornadas em vez de empilhar.",
      "Um fio de azeite ajuda a dourar, mas não é necessário: a gordura da pele dá conta.",
    ],
  },
  {
    id: "sobrecoxa-forno",
    capitulo: "frango",
    titulo: "Sobrecoxa no forno",
    kicker: "PARA MUITAS PEÇAS DE UMA VEZ",
    subtitulo: "A grelha sobre a assadeira é o que separa pele crocante de frango cozido no próprio caldo.",
    porcoes: 4, porcoesOpcoes: [4, 6, 8], ativo: 10, total: 50,
    utensilio: "Assadeira com grelha",
    faixa: "O AR PRECISA CIRCULAR POR BAIXO",
    ingredientes: [
      { q: 8, u: "un", alt: { q: 1440, u: "g" }, nome: "sobrecoxas com pele e osso" },
      { q: 2, u: "col. chá", alt: { q: 12, u: "g" }, nome: "sal" },
      { q: 2, u: "col. chá", alt: { q: 2, u: "g" }, nome: "ervas secas" },
      { q: 1, u: "col. chá", alt: { q: 2, u: "g" }, nome: "pimenta-do-reino", obs: "moída na hora" },
      { q: 1, u: "col. chá", alt: { q: 3, u: "g" }, nome: "páprica", obs: "opcional" },
    ],
    grade: [
      { col: 1, de: 0, ate: 4, titulo: "temperar e secar", detalhe: "papel toalha na pele" },
      { col: 2, de: 0, ate: 4, titulo: "grelha sobre a assadeira", detalhe: "pele para cima, espaçadas" },
      { col: 3, de: 0, ate: 4, titulo: "assar 220 °C", detalhe: "35–40 min" },
      { col: 4, de: 0, ate: 4, titulo: "descansar", detalhe: "5 min" },
    ],
    modo: [
      { t: "Preaqueça o forno a 220 °C. Tempere e seque bem a pele." },
      { t: "Disponha as peças sobre uma grelha encaixada na assadeira, pele para cima. Sem a grelha, a peça assa dentro da própria gordura e a pele de baixo nunca fica crocante." },
      { t: "Asse 35 a 40 minutos, sem virar, até a pele vidrar.", timer: 2100 },
      { t: "Descanse 5 minutos antes de servir.", timer: 300 },
    ],
    notas: [
      "A gordura que pinga na assadeira é ouro: coe e guarde na geladeira por até uma semana.",
      "Forno com ventilação acelera: comece a olhar aos 30 minutos.",
    ],
  },
  {
    id: "batatas-gordura",
    capitulo: "frango",
    titulo: "Batatas na gordura do frango",
    kicker: "MESMA FRIGIDEIRA · SEM LAVAR NADA",
    subtitulo: "Feitas logo depois do frango, na gordura rendida, enquanto a carne descansa.",
    porcoes: 2, porcoesOpcoes: [2, 4, 6], ativo: 20, total: 25,
    utensilio: "A frigideira do frango",
    faixa: "NÃO LAVE A FRIGIDEIRA — A GORDURA É O TEMPERO",
    ingredientes: [
      { q: 500, u: "g", nome: "batatas", obs: "em cubos de 2 cm" },
      { q: 2, u: "col. sopa", alt: { q: 30, u: "ml" }, nome: "gordura rendida do frango", obs: "o que ficou na frigideira" },
      { q: 2, u: "dentes", alt: { q: 10, u: "g" }, nome: "alho", obs: "fatiado" },
      { q: 1, u: "ramo", alt: { q: 2, u: "g" }, nome: "alecrim", obs: "opcional" },
      { q: 0.5, u: "col. chá", alt: { q: 3, u: "g" }, nome: "sal", obs: "só no fim" },
    ],
    grade: [
      { col: 1, de: 0, ate: 0, titulo: "cortar e secar", detalhe: "cubos de 2 cm · papel toalha" },
      { col: 2, de: 0, ate: 1, titulo: "na gordura quente", detalhe: "camada única, sem empilhar" },
      { col: 3, de: 0, ate: 1, titulo: "dourar", detalhe: "12–15 min · mexa pouco" },
      { col: 4, de: 0, ate: 4, titulo: "alho, ervas e sal", detalhe: "2 min no fim" },
    ],
    modo: [
      { t: "Corte as batatas em cubos de 2 cm e seque com papel toalha — batata molhada não doura, cozinha." },
      { t: "Tire o frango da frigideira e deixe a gordura rendida. Se sobrou pouca, complete com azeite até cobrir o fundo." },
      { t: "Ponha os cubos em camada única, sem empilhar, em fogo médio-alto. Se não couberem de uma vez, faça em duas levas." },
      { t: "Doure 12 a 15 minutos, mexendo o mínimo possível — cada mexida interrompe a crosta que está se formando.", timer: 780 },
      { t: "Nos últimos 2 minutos, junte o alho fatiado e o alecrim. Sal só agora: salgar antes puxa água e amolece.", timer: 120 },
    ],
    notas: [
      "Para acelerar: cozinhe os cubos 6 min em água salgada, escorra, seque, e só então doure. A crosta fica melhor ainda.",
      "Para cortar a riqueza do prato, uma salada de folhas com limão puro e sal — sem azeite, a gordura já veio do frango.",
    ],
  },
  {
    id: "arroz-de-alho",
    capitulo: "frango",
    titulo: "Arroz de alho na gordura rendida",
    kicker: "UMA PANELA · 20 MINUTOS",
    subtitulo: "Uma colher da gordura do frango no lugar do óleo muda o arroz inteiro.",
    porcoes: 4, porcoesOpcoes: [2, 4, 6], ativo: 10, total: 25,
    utensilio: "Panela com tampa",
    faixa: "ÁGUA QUENTE — ARROZ NÃO GOSTA DE CHOQUE TÉRMICO",
    ingredientes: [
      { q: 2, u: "xíc.", alt: { q: 360, u: "g" }, nome: "arroz branco", obs: "lavado e escorrido" },
      { q: 2, u: "col. sopa", alt: { q: 30, u: "ml" }, nome: "gordura rendida do frango" },
      { q: 4, u: "dentes", alt: { q: 20, u: "g" }, nome: "alho", obs: "fatiado fino" },
      { q: 3, u: "xíc.", alt: { q: 720, u: "ml" }, nome: "água quente" },
      { q: 1, u: "col. chá", alt: { q: 6, u: "g" }, nome: "sal" },
    ],
    grade: [
      { col: 1, de: 1, ate: 2, titulo: "fritar o alho", detalhe: "2 min · até dourar claro" },
      { col: 2, de: 0, ate: 2, titulo: "refogar o arroz", detalhe: "2 min · grãos translúcidos" },
      { col: 3, de: 0, ate: 4, titulo: "água e sal, ferver", detalhe: "sem tampa, até secar a superfície" },
      { col: 4, de: 0, ate: 4, titulo: "tampar, fogo baixo", detalhe: "15 min · não abra" },
      { col: 5, de: 0, ate: 4, titulo: "descansar e soltar", detalhe: "5 min tampado · garfo" },
    ],
    modo: [
      { t: "Aqueça a gordura rendida e frite o alho fatiado até dourar claro. Alho escuro amarga o arroz inteiro — tire do fogo antes do que parece necessário.", timer: 120 },
      { t: "Junte o arroz lavado e escorrido. Refogue 2 minutos, até os grãos ficarem translúcidos nas bordas.", timer: 120 },
      { t: "Adicione a água quente e o sal. Deixe ferver sem tampa até a água desaparecer da superfície e aparecerem crateras." },
      { t: "Tampe, baixe o fogo ao mínimo e conte 15 minutos. Não abra a panela nesse tempo.", timer: 900 },
      { t: "Desligue e descanse 5 minutos ainda tampado. Solte com um garfo, nunca com colher.", timer: 300 },
    ],
    notas: [
      "Proporção 1 de arroz para 1½ de água. Com gordura no refogado, o grão fica mais solto que com óleo.",
      "Gordura de frango coada guarda uma semana na geladeira e três meses no congelador.",
    ],
  },

  /* ===================== CARNES ===================== */
  {
    id: "prime-rib-chapa",
    capitulo: "carnes",
    titulo: "Prime rib na chapa",
    kicker: "DUAS FASES · PEÇA ALTA DE 4 CM",
    subtitulo: "Selar forte e depois fogo mínimo virando a cada minuto — a chapa vira um forno.",
    porcoes: 1, porcoesOpcoes: [1, 2, 4], ativo: 25, total: 45,
    utensilio: "Chapa removível sobre a boca alta",
    faixa: "GOTA D'ÁGUA DANÇA E SOME EM 1–2 SEGUNDOS",
    ingredientes: [
      { q: 1, u: "peça", alt: { q: 700, u: "g" }, nome: "prime rib", obs: "~4 cm de altura" },
      { q: 1, u: "col. sopa", alt: { q: 12, u: "g" }, nome: "sal grosso", obs: "generoso, só na hora" },
      { q: 1, u: "col. chá", alt: { q: 5, u: "ml" }, nome: "banha ou óleo", obs: "filme fino na chapa" },
      { q: 0.5, u: "col. chá", alt: { q: 1, u: "g" }, nome: "pimenta-do-reino", obs: "só depois de selar" },
    ],
    grade: [
      { col: 1, de: 0, ate: 0, titulo: "secar e atemperar", detalhe: "papel toalha · 30–40 min fora da geladeira" },
      { col: 2, de: 0, ate: 1, titulo: "salgar na hora", detalhe: "generoso, só ao ir para a chapa" },
      { col: 3, de: 0, ate: 2, titulo: "selar na chapa quente", detalhe: "2–3 min por lado" },
      { col: 4, de: 0, ate: 3, titulo: "fogo mínimo, virar a cada minuto", detalhe: "6–10 min · cut-and-peek" },
      { col: 5, de: 0, ate: 3, titulo: "selar as bordas de gordura", detalhe: "30 s na vertical, com pinça" },
      { col: 6, de: 0, ate: 3, titulo: "descansar", detalhe: "8–10 min" },
    ],
    modo: [
      { t: "Seque muito bem com papel toalha e deixe 30 a 40 minutos fora da geladeira. Centro gelado é o maior inimigo." },
      { t: "Pré-aqueça a chapa 5 a 8 minutos em registro baixo-médio, para o calor espalhar. A chama concentra no centro, então sele no centro mesmo. Teste com uma gota d'água: ela deve dançar e sumir em 1 a 2 segundos.", timer: 420 },
      { t: "Sal generoso só agora. Filme fino de banha ou óleo na chapa quente." },
      { t: "Sele 2 a 3 minutos de cada lado, até formar crosta bonita.", timer: 150 },
      { t: "Baixe para o fogo mínimo e vire a cada minuto por mais 6 a 10 minutos, conforme o ponto. Virar com frequência cozinha o centro de forma uniforme.", timer: 480 },
      { t: "Sele as bordas de gordura na vertical, cerca de 30 segundos, segurando com a pinça. Pimenta-do-reino agora — antes ela queima.", timer: 30 },
      { t: "A partir dos 6 minutos de fogo baixo, faça um corte pequeno no centro e espie: ao ponto para menos é rosado quente; vermelho frio pede mais tempo." },
      { t: "Descanse 8 a 10 minutos. Peça alta precisa desse tempo para redistribuir os sucos.", timer: 540 },
    ],
    notas: [
      "Peça fina (~2 cm) é outro método: 2 a 2,5 minutos por lado virando uma vez só, 20–30 min fora da geladeira, descanso de 5 min. Cada 30 segundos a mais muda o ponto.",
      "Molho de fond: devolva a chapa ao fogo baixo e deglaceie com um pouco de cachaça ou shoyu mais manteiga. Se levar shoyu, alivie o sal do resto do prato.",
      "Use a chapa removível, não a integrada: a boca alta tem calor de recuperação melhor.",
    ],
  },
  {
    id: "smashed-potatoes",
    capitulo: "carnes",
    titulo: "Smashed potatoes na air fryer",
    kicker: "SUPERFÍCIE IRREGULAR · GORDURA GENEROSA · NÃO MEXER",
    subtitulo: "Rachaduras e bordas soltas são o que vira crocância. Não tente arrumar.",
    porcoes: 2, porcoesOpcoes: [2, 4], ativo: 15, total: 40,
    utensilio: "Air fryer",
    faixa: "GORDURA DE MENOS É O ERRO Nº 1 NA AIR FRYER",
    ingredientes: [
      { q: 4, u: "un", alt: { q: 600, u: "g" }, nome: "batatas médias", obs: "inteiras, com casca" },
      { q: 1, u: "col. sopa", alt: { q: 15, u: "g" }, nome: "sal grosso", obs: "para a água" },
      { q: 3, u: "col. sopa", alt: { q: 45, u: "ml" }, nome: "banha ou azeite", obs: "dos dois lados" },
      { q: 1, u: "pitada", alt: { q: 2, u: "g" }, nome: "sal fino", obs: "leve, por cima", escala: false },
      { q: 1, u: "ramo", alt: { q: 2, u: "g" }, nome: "alecrim" },
    ],
    grade: [
      { col: 1, de: 0, ate: 1, titulo: "cozinhar inteiras", detalhe: "água bem salgada · ~20 min" },
      { col: 2, de: 0, ate: 1, titulo: "escorrer e secar", detalhe: "2–3 min soltando vapor" },
      { col: 3, de: 0, ate: 1, titulo: "amassar com o fundo do copo", detalhe: "até ~1,5 cm · rachaduras = crocância" },
      { col: 4, de: 0, ate: 4, titulo: "gordura, sal e alecrim", detalhe: "dos dois lados, inclusive nos pedacinhos" },
      { col: 5, de: 0, ate: 4, titulo: "air fryer 200 °C", detalhe: "15–18 min · sem virar e sem mexer" },
    ],
    modo: [
      { t: "Cozinhe as batatas inteiras em água bem salgada até o garfo entrar fácil, cerca de 20 minutos.", timer: 1200 },
      { t: "Escorra e deixe secar 2 a 3 minutos soltando vapor.", timer: 150 },
      { t: "Amasse cada uma com o fundo de um copo até uns 1,5 cm. Rachaduras e bordas irregulares são o que vira crocância — não re-formate se desmontar." },
      { t: "Gordura generosa dos dois lados, inclusive nos pedacinhos soltos. Sal leve por cima (a água já salgou por dentro) e alecrim." },
      { t: "Air fryer a 200 °C por 15 a 18 minutos, sem virar e sem mexer. Cesta pequena: duas levas de duas batatas — amontoada não croca.", timer: 1000 },
    ],
    notas: [
      "Batata muito cozida solta mais umidade: compense com mais gordura.",
      "Se precisarem esperar, 2 a 3 minutos de volta na air fryer re-crocam.",
      "Forno para quatro batatas é desperdício — a circulação de ar da air fryer croca até mais.",
    ],
  },
  {
    id: "medalhoes-suinos",
    capitulo: "carnes",
    titulo: "Medalhões de filé mignon suíno ao molho de mostarda",
    kicker: "ALMOÇO A DOIS · SELAR E TERMINAR NO MOLHO",
    subtitulo: "Corte magro: sela só para a crosta e deixa o molho terminar o cozimento devagar.",
    porcoes: 2, porcoesOpcoes: [2, 4], ativo: 30, total: 35,
    utensilio: "Inox de fundo grosso ou ferro fundido",
    faixa: "SELE COM O CENTRO AINDA CRU — O MOLHO TERMINA",
    ingredientes: [
      { q: 650, u: "g", nome: "filé mignon suíno", obs: "2 cordões, em medalhões de 2,5 cm" },
      { q: 1, u: "col. chá", alt: { q: 6, u: "g" }, nome: "sal", obs: "leve — o shoyu já salga" },
      { q: 0.5, u: "col. chá", alt: { q: 1, u: "g" }, nome: "pimenta-do-reino", obs: "moída na hora" },
      { q: 1, u: "col. sopa", alt: { q: 15, u: "ml" }, nome: "óleo" },
      { q: 2, u: "col. sopa", alt: { q: 30, u: "g" }, nome: "manteiga gelada", obs: "metade no início, metade no fim" },
      { q: 1, u: "dente", alt: { q: 5, u: "g" }, nome: "alho", obs: "amassado" },
      { q: 2, u: "col. sopa", alt: { q: 30, u: "ml" }, nome: "cachaça" },
      { q: 1, u: "col. sopa", alt: { q: 15, u: "g" }, nome: "mostarda Dijon" },
      { q: 1, u: "col. sopa", alt: { q: 15, u: "ml" }, nome: "shoyu" },
      { q: 100, u: "ml", nome: "creme de leite" },
    ],
    grade: [
      { col: 1, de: 0, ate: 0, titulo: "cortar 2,5 cm e secar", detalhe: "a ponta fina dobra com palito" },
      { col: 2, de: 0, ate: 2, titulo: "temperar só na hora", detalhe: "sal leve e pimenta" },
      { col: 3, de: 0, ate: 3, titulo: "selar e retirar", detalhe: "2 min · virar · 2 min · centro cru" },
      { col: 4, de: 4, ate: 5, titulo: "manteiga e alho", detalhe: "só até perfumar" },
      { col: 5, de: 4, ate: 6, titulo: "fora do fogo: cachaça", detalhe: "volte e raspe o fond" },
      { col: 6, de: 4, ate: 9, titulo: "mostarda, shoyu e creme", detalhe: "reduzir até cobrir a colher" },
      { col: 7, de: 0, ate: 9, titulo: "devolver a carne", detalhe: "aquecer gentil · provar o sal" },
    ],
    modo: [
      { t: "Corte os medalhões com cerca de 2,5 cm de altura. O que manda no ponto é a espessura, não o diâmetro — se uns saírem mais largos, tudo bem. A ponta fina dobra sobre si mesma e prende com um palito para ganhar altura." },
      { t: "Seque muito bem com papel toalha. Carne úmida cozinha no vapor, não doura. Tempere com sal e pimenta só na hora de ir para a panela." },
      { t: "Panela quente com o óleo. Acomode sem amontoar — se a panela for de fundo fino, sele em lotes pequenos e deixe ela recuperar entre um e outro." },
      { t: "Sele 2 minutos, vire, mais 2 minutos — só até a crosta dourada dos dois lados. O centro fica cru de propósito. Retire e reserve num prato.", timer: 240 },
      { t: "Abaixe para fogo médio. Junte metade da manteiga e o alho amassado; refogue só até perfumar — nessa boca o alho queima em segundos." },
      { t: "Tire a panela do fogo e adicione a cachaça (álcool em panela muito quente pode inflamar). Volte ao fogo e raspe o fundo para soltar o fond." },
      { t: "Junte a mostarda, o shoyu e o creme de leite. Mexa e reduza em fogo baixo até encorpar e cobrir as costas da colher." },
      { t: "Desligue e incorpore a manteiga gelada restante para dar brilho." },
      { t: "Devolva os medalhões e o líquido que soltaram; aqueça gentilmente só para terminar o ponto. Rosado claro com sucos rosados = pronto. Prove o molho antes de acertar o sal." },
    ],
    notas: [
      "Evite antiaderente: quase não forma fond, e o molho fica sem graça.",
      "Variação clássica: troque o shoyu por uma pitada extra de sal e capriche na mostarda. Variação leve: pule o creme e faça só a redução de cachaça com manteiga gelada.",
      "Acompanhamentos: arroz branco, purê ou batatas douradas, e pão para aproveitar o molho.",
    ],
  },
  {
    id: "fraldinha-forno",
    capitulo: "carnes",
    titulo: "Fraldinha marinada assada no forno",
    kicker: "PEÇA INTEIRA · FATIADA NA MESA",
    subtitulo: "Servida quente, ao ponto+, fatiada fino contra as fibras na hora de servir.",
    porcoes: 4, porcoesOpcoes: [4, 6, 8], ativo: 20, total: 185,
    utensilio: "Assadeira e papel alumínio",
    faixa: "A MARINADA TEM QUATRO FONTES DE SÓDIO — PROVE ANTES",
    ingredientes: [
      { q: 1.2, u: "kg", alt: { q: 1200, u: "g" }, nome: "fraldinha", obs: "peça inteira" },
      { q: null, u: "", nome: "sal" },
      { q: null, u: "", nome: "shoyu" },
      { q: null, u: "", nome: "molho inglês", obs: "Worcestershire" },
      { q: null, u: "", nome: "nam pla", obs: "molho de peixe" },
      { q: null, u: "", nome: "vinagre" },
      { q: null, u: "", nome: "cerveja" },
      { q: null, u: "", nome: "louro" },
      { q: null, u: "", nome: "pimenta-do-reino" },
      { q: null, u: "", nome: "pimenta-da-Jamaica" },
    ],
    grade: [
      { col: 1, de: 1, ate: 9, titulo: "montar a marinada", detalhe: "provar o líquido antes de usar" },
      { col: 2, de: 0, ate: 9, titulo: "marinar 2 h", detalhe: "geladeira" },
      { col: 3, de: 0, ate: 9, titulo: "1 h fora da geladeira", detalhe: "e secar bem a superfície" },
      { col: 4, de: 0, ate: 9, titulo: "coberta com alumínio, 200 °C", detalhe: "checar a partir dos 45 min" },
      { col: 5, de: 0, ate: 9, titulo: "sem alumínio + grill", detalhe: "só para corar" },
      { col: 6, de: 0, ate: 9, titulo: "descansar e fatiar", detalhe: "8–10 min · fino, contra as fibras" },
    ],
    modo: [
      { t: "Monte a marinada com sal, shoyu, molho inglês, nam pla, vinagre, cerveja, louro, pimenta-do-reino e pimenta-da-Jamaica. São quatro fontes de sódio juntas — prove o líquido antes de usá-lo também como molho." },
      { t: "Marine 2 horas na geladeira." },
      { t: "Tire da geladeira 1 hora antes de ir para o forno. Centro frio é o maior inimigo sem termômetro.", timer: 3600 },
      { t: "Seque bem a superfície com papel toalha — a marinada encharca a carne." },
      { t: "Cubra com papel alumínio e leve ao forno a 200 °C." },
      { t: "Comece a checar aos 45 minutos: faça um corte no ponto mais grosso e leia a cor. Vermelho frio no centro segue; rosa quente é mal para ao ponto; levemente rosado, quase sem rosa e ainda úmido é o ponto+, o ideal. Cinza por igual é bem passado e não volta atrás.", timer: 2700 },
      { t: "Perto do ponto, tire o alumínio e ligue o grill só para corar a superfície." },
      { t: "Descanse 8 a 10 minutos antes de fatiar. Não pule.", timer: 540 },
      { t: "Leve a peça inteira e quente à mesa e fatie na hora, bem fino e contra as fibras — é o fator que mais pesa na maciez deste corte." },
    ],
    notas: [
      "Tempo total aproximado: 50 a 65 minutos de forno para peça de ~1,2 kg a 200 °C.",
      "Molho opcional: reduza o líquido da marinada em fogo baixo até concentrar. Prove o sal antes — a redução intensifica bastante.",
      "Reaquecimento destrói: fraldinha ao ponto que volta ao fogo vira borracha. Se não dá para servir na hora, faça braseado (150–160 °C, 2h30–3h com líquido cobrindo) ou rosbife frio.",
    ],
  },

  /* ===================== FEIJOADA ===================== */
  {
    id: "feijoada",
    capitulo: "feijoada",
    titulo: "Feijoada completa",
    kicker: "TRÊS DIAS · 10 A 15 PESSOAS · SOBRA PARA CONGELAR",
    subtitulo:
      "Dessalga correta, sequência de entrada das carnes e fogo baixo por 4 a 5 horas. O resto é paciência.",
    porcoes: 20, porcoesOpcoes: [10, 20, 30], ativo: 180, total: 300,
    utensilio: "Caldeirão de 28 cm (~10 L)",
    faixa: "3 KG DE CARNE PARA 1 KG DE FEIJÃO · SAL SÓ NO FINAL",
    ingredientes: [
      { q: 828, u: "g", nome: "carne seca", obs: "em cubos de 3 cm" },
      { q: 1220, u: "g", nome: "costela suína salgada", obs: "em cubos de 3 cm" },
      { q: 518, u: "g", nome: "orelha de porco salgada" },
      { q: 276, u: "g", nome: "rabo de porco salgado" },
      { q: 1500, u: "g", nome: "feijão preto", obs: "de molho por 30 min" },
      { q: 5, u: "un", alt: { q: 700, u: "g" }, nome: "cebolas grandes", obs: "picadas fino" },
      { q: 8, u: "dentes", alt: { q: 40, u: "g" }, nome: "alho", obs: "picado fino" },
      { q: 0.33, u: "xíc.", alt: { q: 70, u: "g" }, nome: "banha", obs: "melhor que azeite aqui" },
      { q: 1.5, u: "col. chá", alt: { q: 4, u: "g" }, nome: "cominho em pó" },
      { q: 5, u: "folhas", alt: { q: 2, u: "g" }, nome: "louro" },
      { q: 7, u: "l", nome: "água", obs: "proporcional ao feijão" },
      { q: 1, u: "un", alt: { q: 200, u: "g" }, nome: "laranja inteira com casca" },
      { q: 1000, u: "g", nome: "lombo suíno salgado" },
      { q: 366, u: "g", nome: "paio", obs: "inteiro" },
      { q: 460, u: "g", nome: "calabresa", obs: "inteira" },
      { q: null, u: "", nome: "sal e pimenta-do-reino", obs: "só no fim, provando", escala: false },
    ],
    grade: [
      { col: 1, de: 0, ate: 3, titulo: "dessalgar 24 h", detalhe: "cubos de 3 cm · trocar a água a cada 3–4 h" },
      { col: 2, de: 0, ate: 3, titulo: "ferventar 10 min", detalhe: "descartar a água" },
      { col: 3, de: 5, ate: 9, titulo: "refogar na banha", detalhe: "cebola 8 min · alho, cominho e louro 1 min" },
      { col: 4, de: 0, ate: 10, titulo: "feijão, carnes e água", detalhe: "fogo alto até ferver" },
      { col: 5, de: 0, ate: 11, titulo: "laranja e fogo mínimo", detalhe: "tampa entreaberta · ~1h40" },
      { col: 6, de: 0, ate: 14, titulo: "lombo ferventado, paio e calabresa", detalhe: "inteiros · +2 h mexendo a cada 20–30 min" },
      { col: 7, de: 0, ate: 14, titulo: "tirar a laranja, fatiar as linguiças", detalhe: "espremer o caldo da laranja antes" },
      { col: 8, de: 0, ate: 15, titulo: "provar o sal e apurar", detalhe: "amassar feijão · descansar 5–10 min" },
    ],
    modo: [
      { t: "Dia 1 — Dessalga. Corte as carnes salgadas em cubos de 3 cm, cubra com bastante água em tigelas separadas e leve à geladeira. Troque a água a cada 3 ou 4 horas ao longo do dia. Vinte e quatro horas é o ideal." },
      { t: "Dia 2, 5h45 — Ferventa as carnes salgadas num caldeirão com água. Dez minutos após ferver, descarte a água e reserve as carnes.", timer: 600 },
      { t: "6h30 — Refogue a cebola na banha até dourar, cerca de 8 minutos. Adicione o alho, o cominho e o louro e mexa 1 minuto. Se pegar um pouco no fundo, tudo bem: fond é sabor, e você deglaceia depois.", timer: 480 },
      { t: "6h50 — Adicione o feijão (que ficou de molho 30 min), 6 a 8 litros de água e as carnes ferventadas. Fogo alto até ferver." },
      { t: "7h40 — Na fervura, acrescente a laranja inteira, abaixe para o fogo mínimo e deixe a tampa entreaberta." },
      { t: "9h20 — Ferventa o lombo separadamente por 10 minutos e adicione à panela, junto com o paio e a calabresa inteiros. Não coloque bacon: ele todo vai para a farofa.", timer: 600 },
      { t: "9h20 às 11h30 — Mexa a cada 20 ou 30 minutos, raspando delicadamente o fundo. Confira o nível de água: as carnes têm que ficar cobertas. Complete se precisar." },
      { t: "10h30 — Tire a laranja e esprema o caldo dela na panela antes de descartar. Deixar mais tempo amarga." },
      { t: "11h50 — Tire o paio e a calabresa, corte em rodelas de 1 cm na diagonal e devolva à panela." },
      { t: "12h — Prove o sal pela primeira vez. Provavelmente nem precisa. Se o caldo estiver ralo, amasse um pouco do feijão contra a parede da panela com o dorso da concha." },
      { t: "12h20 — Desligue. Descanse 5 a 10 minutos com a tampa entreaberta antes de servir: o caldo termina de engrossar.", timer: 600 },
    ],
    notas: [
      "Feijoada tem várias fontes de sal: carnes salgadas, paio, calabresa. Nunca sale antes de provar no final.",
      "1,5 kg de feijão fica carnuda; 2 kg dá mais caldo para dividir. Teste 2 kg se o grupo passar de 15.",
      "Bacon todo na farofa: a feijoada já tem gordura de sobra com paio, calabresa, costela e lombo.",
      "Congela muito bem e melhora no dia seguinte. Separe potes limpos antes de servir. Para descongelar: geladeira 24 h antes, requentar em fogo baixo mexendo.",
      "Molho de pimenta: Tabasco é o clássico, biquinho em conserva é o suave universal. Sriracha e sweet chilli não combinam — perfil errado.",
    ],
  },
  {
    id: "farofa-bacon",
    capitulo: "feijoada",
    titulo: "Farofa de bacon com azeitona",
    kicker: "SEPARE METADE DA GORDURA PARA A COUVE",
    subtitulo: "O bacon inteiro da feijoada vem parar aqui — rende mais como farofa crocante.",
    porcoes: 20, porcoesOpcoes: [10, 20, 30], ativo: 25, total: 25,
    utensilio: "Frigideira grande",
    faixa: "FARINHA AOS POUCOS, MEXENDO SEMPRE",
    ingredientes: [
      { q: 240, u: "g", nome: "bacon", obs: "em cubos de 1 cm" },
      { q: 1, u: "un", alt: { q: 140, u: "g" }, nome: "cebola média", obs: "picada" },
      { q: 2, u: "dentes", alt: { q: 10, u: "g" }, nome: "alho", obs: "picado" },
      { q: 2, u: "xíc.", alt: { q: 300, u: "g" }, nome: "farinha de mandioca", obs: "fina ou biju" },
      { q: 0.5, u: "xíc.", alt: { q: 70, u: "g" }, nome: "azeitonas", obs: "picadas" },
      { q: 2, u: "col. sopa", alt: { q: 8, u: "g" }, nome: "salsinha", obs: "picada" },
      { q: 0.5, u: "col. chá", alt: { q: 1, u: "g" }, nome: "pimenta-do-reino", obs: "moída na hora" },
    ],
    grade: [
      { col: 1, de: 0, ate: 0, titulo: "fritar o bacon", detalhe: "~7 min · retirar com escumadeira" },
      { col: 2, de: 0, ate: 0, titulo: "separar metade da gordura", detalhe: "reservar para a couve" },
      { col: 3, de: 0, ate: 2, titulo: "refogar cebola e alho", detalhe: "5 min + 1 min" },
      { col: 4, de: 0, ate: 3, titulo: "voltar o bacon, fogo baixo" },
      { col: 5, de: 0, ate: 3, titulo: "farinha aos poucos, torrar", detalhe: "7–10 min · mexendo sempre" },
      { col: 6, de: 0, ate: 6, titulo: "salsinha, azeitona e pimenta", detalhe: "provar o sal" },
    ],
    modo: [
      { t: "Frite o bacon em cubos de 1 cm até dourar, cerca de 7 minutos. Tire com escumadeira e reserve.", timer: 420 },
      { t: "Separe metade da gordura numa tigelinha, para a couve. Esse passo é crucial — couve com gordura de bacon é imbatível." },
      { t: "Na gordura restante, refogue a cebola picada até dourar, cerca de 5 minutos. Adicione o alho e refogue mais 1 minuto.", timer: 300 },
      { t: "Volte o bacon à frigideira e abaixe o fogo." },
      { t: "Adicione a farinha aos poucos, mexendo sempre. Torre 7 a 10 minutos até dourar — farinha fina precisa de mais torra que biju.", timer: 540 },
      { t: "No final, junte a salsinha picada, as azeitonas e a pimenta-do-reino moída na hora. Prove o sal. Reserve tampada." },
    ],
    notas: [
      "Ovo mexido antes da farinha faz uma farofa premium.",
      "O bacon é a única fonte de gordura aqui, e já é bastante — não acrescente óleo.",
    ],
  },
  {
    id: "couve-bacon",
    capitulo: "feijoada",
    titulo: "Couve na gordura de bacon",
    kicker: "CHIFFONADE NA FACA · NUNCA NO PROCESSADOR",
    subtitulo: "Dois a três minutos de frigideira. Passou do ponto, perdeu.",
    porcoes: 20, porcoesOpcoes: [10, 20, 30], ativo: 15, total: 15,
    utensilio: "Frigideira bem quente",
    faixa: "TEM QUE SAIR VERDE-VIBRANTE",
    ingredientes: [
      { q: 3, u: "maços", alt: { q: 450, u: "g" }, nome: "couve manteiga", obs: "em chiffonade de 2–3 mm" },
      { q: 2, u: "col. sopa", alt: { q: 30, u: "ml" }, nome: "gordura de bacon", obs: "a que você reservou da farofa" },
      { q: 1, u: "dente", alt: { q: 5, u: "g" }, nome: "alho", obs: "picado" },
      { q: 0.5, u: "col. chá", alt: { q: 3, u: "g" }, nome: "sal", obs: "no fim" },
    ],
    grade: [
      { col: 1, de: 0, ate: 0, titulo: "chiffonade fina", detalhe: "empilhar, enrolar apertado, fatiar 2–3 mm" },
      { col: 2, de: 1, ate: 2, titulo: "frigideira bem quente", detalhe: "gordura e alho" },
      { col: 3, de: 0, ate: 3, titulo: "saltear", detalhe: "2–3 min · mexendo rápido" },
    ],
    modo: [
      { t: "Empilhe as folhas, enrole apertado e fatie bem fino — 2 a 3 mm, com faca. Processador amassa a folha, dá corte irregular e oxida." },
      { t: "Frigideira bem quente com a gordura reservada do bacon e o alho picado." },
      { t: "Jogue a couve e mexa rápido por 2 a 3 minutos. Sal no fim. Não pode passar do ponto: tem que ficar verde-vibrante.", timer: 150 },
    ],
    notas: [
      "É o último item a sair da cozinha, imediatamente antes de servir.",
      "Sem feijoada no dia? Gordura de bacon guardada na geladeira faz o mesmo serviço.",
    ],
  },

  /* ===================== ARROZ E MASSAS ===================== */
  {
    id: "fried-rice",
    capitulo: "arroz",
    titulo: "Fried rice de bacon e calabresa",
    kicker: "15 MINUTOS · ARROZ DE ONTEM É OBRIGATÓRIO",
    subtitulo: "A ordem é o método: cada etapa aproveita a gordura da anterior.",
    porcoes: 2, porcoesOpcoes: [2, 4], ativo: 15, total: 15,
    utensilio: "Wok ou frigideira grande",
    faixa: "MISE EN PLACE ANTES DE LIGAR O FOGO",
    ingredientes: [
      { q: 80, u: "g", nome: "bacon", obs: "em cubinhos" },
      { q: 80, u: "g", nome: "linguiça calabresa", obs: "fatiada bem fina" },
      { q: 2, u: "un", alt: { q: 110, u: "g" }, nome: "ovos grandes", obs: "batidos" },
      { q: 2, u: "col. chá", alt: { q: 8, u: "g" }, nome: "gengibre", obs: "ralado" },
      { q: 3, u: "xíc.", alt: { q: 450, u: "g" }, nome: "arroz branco de ontem", obs: "frio e esfarelado" },
      { q: 1.5, u: "col. sopa", alt: { q: 22, u: "ml" }, nome: "shoyu", obs: "pela borda da panela" },
      { q: 1, u: "col. sopa", alt: { q: 15, u: "ml" }, nome: "sake seco" },
      { q: 1, u: "pitada", alt: { q: 1, u: "g" }, nome: "aji-no-moto", obs: "opcional", escala: false },
      { q: 1, u: "col. chá", alt: { q: 5, u: "ml" }, nome: "óleo de gergelim", obs: "fora do fogo" },
      { q: null, u: "", nome: "togarashi", obs: "a gosto, para finalizar" },
      { q: null, u: "", nome: "cebolinha", obs: "picada, opcional" },
    ],
    grade: [
      { col: 1, de: 0, ate: 0, titulo: "fritar o bacon", detalhe: "reservar · deixar toda a gordura" },
      { col: 2, de: 1, ate: 1, titulo: "dourar a calabresa", detalhe: "até pegar cor nas bordas" },
      { col: 3, de: 2, ate: 2, titulo: "ovos na mesma gordura", detalhe: "tirar ainda cremoso" },
      { col: 4, de: 3, ate: 3, titulo: "gengibre no fogo alto", detalhe: "segundos, só até perfumar" },
      { col: 5, de: 3, ate: 4, titulo: "arroz espalhado, parado", detalhe: "uns segundos antes de mexer" },
      { col: 6, de: 3, ate: 7, titulo: "shoyu pela borda, sake, aji", detalhe: "misturar rápido" },
      { col: 7, de: 0, ate: 7, titulo: "juntar tudo", detalhe: "só até aquecer" },
      { col: 8, de: 0, ate: 10, titulo: "fora do fogo", detalhe: "gergelim, togarashi, cebolinha" },
    ],
    modo: [
      { t: "Mise en place primeiro — o salteado é rápido demais para picar no meio. Esfarele o arroz com as mãos, fatie a calabresa fina, bata os ovos, rale o gengibre. Tudo ao alcance antes de ligar o fogo." },
      { t: "Panela quase seca, fogo médio. Frite o bacon até render e ficar dourado e crocante. Retire com escumadeira e deixe toda a gordura na panela — é a base de tudo." },
      { t: "Na gordura do bacon, doure a calabresa até pegar cor nas bordas. Retire e reserve junto com o bacon." },
      { t: "Despeje os ovos batidos na mesma gordura e mexa em fogo médio, puxando do fundo. Tire ainda mole e cremoso, antes de secar — ele termina de cozinhar depois." },
      { t: "Suba para o fogo alto. Jogue o gengibre e mexa só até perfumar, sem queimar — nessa boca são segundos." },
      { t: "Entra o arroz esfarelado. Espalhe numa camada e deixe parado uns segundos para pegar na panela antes de mexer — é isso que dá o tostadinho. Depois salteie até os grãos soltarem e dourarem de leve." },
      { t: "Regue o shoyu pela borda da panela, que carameliza melhor que jogado por cima. Splash de sake para soltar o fundo, pitada de aji. Misture rápido." },
      { t: "Devolva bacon, calabresa e ovo. Misture só até aquecer e o ovo se quebrar em pedaços pelo arroz." },
      { t: "Fora do fogo: fio de óleo de gergelim, togarashi e cebolinha. Prove e corrija — dificilmente vai precisar de sal." },
    ],
    notas: [
      "Arroz frio de véspera é obrigatório: o grão perdeu umidade e frita solto. Arroz quente recém-feito solta vapor e empapa.",
      "Bacon dá gordura e crocância defumada; calabresa entra em pouca quantidade só pela páprica e pelo alho. Sem ela, compense com mais gengibre e shoyu.",
      "Sem miso: no calor da panela ele empelota, queima e vira pasta. Lugar dele é sopa, marinada ou molho de tigela.",
      "Quatro fontes de sódio juntas — bacon, calabresa, shoyu e aji. Prove antes de pensar em sal.",
    ],
  },
  {
    id: "risone-camarao",
    capitulo: "arroz",
    titulo: "Risone de camarão ao limão",
    kicker: "RISOTTATO · SEM QUEIJO · CREMOSO PELO AMIDO",
    subtitulo: "Camarão já cozido só reaquece no fim. O hondashi supre o fundo marinho que falta.",
    porcoes: 2, porcoesOpcoes: [2, 4], ativo: 25, total: 30,
    utensilio: "Frigideira grande, borda de 4–5 cm",
    faixa: "PARE NO AL DENTE, MESMO QUE SOBRE CALDO",
    ingredientes: [
      { q: 600, u: "ml", nome: "água quente", obs: "+ chaleira de reserva" },
      { q: 1, u: "tablete", alt: { q: 10, u: "g" }, nome: "caldo de legumes" },
      { q: 1, u: "col. chá", alt: { q: 4, u: "g" }, nome: "hondashi", obs: "até 1½ se quiser mais marcado" },
      { q: 3, u: "col. sopa", alt: { q: 45, u: "ml" }, nome: "azeite", obs: "+ um fio para finalizar" },
      { q: 0.5, u: "un", alt: { q: 70, u: "g" }, nome: "cebola média", obs: "picada fininha" },
      { q: 2, u: "dentes", alt: { q: 10, u: "g" }, nome: "alho" },
      { q: 160, u: "g", nome: "risone", obs: "orzo" },
      { q: 90, u: "g", nome: "vagem congelada", obs: "em pedaços de 2 cm" },
      { q: 300, u: "g", nome: "camarão cozido descascado", obs: "descongelado e bem escorrido" },
      { q: 1, u: "un", alt: { q: 60, u: "g" }, nome: "limão-taíti", obs: "raspas + suco" },
      { q: 1, u: "col. chá", alt: { q: 3, u: "g" }, nome: "lemon pepper" },
      { q: null, u: "", nome: "sal", obs: "só se precisar, no fim", escala: false },
    ],
    grade: [
      { col: 1, de: 0, ate: 2, titulo: "caldo quente ao lado", detalhe: "dissolver tablete e hondashi" },
      { col: 2, de: 3, ate: 5, titulo: "refogar cebola e alho", detalhe: "médio-baixo · sem dourar" },
      { col: 3, de: 3, ate: 6, titulo: "tostar o risone", detalhe: "1–2 min · até perfumar" },
      { col: 4, de: 0, ate: 6, titulo: "caldo concha a concha", detalhe: "esperar absorver antes da próxima" },
      { col: 5, de: 0, ate: 7, titulo: "vagem congelada", detalhe: "6–7 min antes do fim" },
      { col: 6, de: 0, ate: 8, titulo: "camarão, fogo mínimo", detalhe: "1–2 min só para aquecer" },
      { col: 7, de: 0, ate: 11, titulo: "fora do fogo", detalhe: "raspas, suco, lemon pepper, azeite · provar" },
    ],
    modo: [
      { t: "Aqueça os 600 ml de água com o tablete de legumes e o hondashi até dissolver. Mantenha quente em fogo baixo ao lado, com uma chaleira de água quente de reserva." },
      { t: "Escorra o camarão muito bem e seque com papel-toalha. Ele já vem cozido — entra só no fim. Reserve." },
      { t: "Azeite em fogo médio-baixo, refogue a cebola até translúcida. Junte o alho e refogue 1 minuto, sem dourar — nessa boca o alho queima em segundos." },
      { t: "Junte o risone seco e mexa 1 a 2 minutos em fogo médio, até perfumar e dourar de leve. Dá sabor e segura o ponto.", timer: 90 },
      { t: "Adicione o caldo quente concha a concha, mexendo e esperando absorver antes da próxima. Fogo médio, borbulhar constante e alegre." },
      { t: "Uns 6 a 7 minutos antes do fim, junte a vagem ainda congelada, direto na panela.", timer: 400 },
      { t: "Comece a provar aos 7 ou 8 minutos. Risone é rápido — pare no al dente, mesmo que sobre caldo. O ponto manda, não o relógio." },
      { t: "Fogo no mínimo ou desligado. Junte o camarão só para aquecer, 1 a 2 minutos. Nunca mais que isso.", timer: 90 },
      { t: "Fora do fogo: raspas e metade do suco do limão, lemon pepper, um fio de azeite. Mexa bem para ficar cremoso e solto (all'onda); se precisar, mais uma concha de caldo. Prove antes de pensar em sal." },
      { t: "Sirva na hora — risone continua absorvendo e engrossa parado." },
    ],
    notas: [
      "600 ml, não 700: o que entra de fato são uns 500 a 550 ml, o resto é folga. O erro é despejar tudo de uma vez e afogar a massa.",
      "Frigideira larga e baixa cozinha numa camada fina e solta amido melhor. Panela funda empilha a massa e empapa embaixo.",
      "Caldo de carne fica de fora: sabor de boi briga com o camarão.",
      "Uma colherzinha de manteiga gelada batida no fim deixa mais sedoso, se quiser.",
    ],
  },

  /* ===================== CONSERVAS ===================== */
  {
    id: "escabeche-sardinha",
    capitulo: "conservas",
    titulo: "Escabeche de sardinha",
    kicker: "PETISCO · MELHOR NO DIA SEGUINTE · NUNCA REAQUECE",
    subtitulo: "Frita rápido e curte num banho morno de vinagre, azeite e aromáticos.",
    porcoes: 4, porcoesOpcoes: [2, 4, 8], ativo: 40, total: 280,
    utensilio: "Refratário de vidro ou cerâmica",
    faixa: "RECIPIENTE NÃO-REATIVO · TUDO SUBMERSO",
    ingredientes: [
      { q: 600, u: "g", nome: "sardinha fresca", obs: "espalmada" },
      { q: 1, u: "col. chá", alt: { q: 6, u: "g" }, nome: "sal e pimenta", obs: "dos dois lados" },
      { q: 2, u: "col. sopa", alt: { q: 20, u: "g" }, nome: "farinha de trigo", obs: "opcional, para empanar leve" },
      { q: 120, u: "ml", nome: "azeite de oliva" },
      { q: 2, u: "un", alt: { q: 280, u: "g" }, nome: "cebolas médias", obs: "em meia-lua fina" },
      { q: 4, u: "dentes", alt: { q: 20, u: "g" }, nome: "alho", obs: "fatiados" },
      { q: 1, u: "un", alt: { q: 80, u: "g" }, nome: "cenoura pequena", obs: "em rodelas finas, opcional" },
      { q: 2, u: "folhas", alt: { q: 1, u: "g" }, nome: "louro" },
      { q: 1, u: "col. chá", alt: { q: 3, u: "g" }, nome: "pimenta-do-reino em grãos" },
      { q: 120, u: "ml", nome: "vinagre de vinho branco", obs: "ou de arroz, mais suave" },
      { q: 60, u: "ml", nome: "vinho branco seco", obs: "opcional" },
      { q: 60, u: "ml", nome: "água" },
      { q: 1, u: "col. chá", alt: { q: 4, u: "g" }, nome: "açúcar", obs: "equilibra a acidez" },
      { q: null, u: "", nome: "salsinha", obs: "picada, para servir" },
    ],
    grade: [
      { col: 1, de: 0, ate: 1, titulo: "secar e temperar", detalhe: "papel-toalha · dos dois lados" },
      { col: 2, de: 0, ate: 3, titulo: "fritar em levas", detalhe: "1–2 min por lado · só dourar" },
      { col: 3, de: 3, ate: 8, titulo: "refogar os aromáticos", detalhe: "médio-baixo · cebola translúcida" },
      { col: 4, de: 3, ate: 12, titulo: "vinagre, vinho, água e açúcar", detalhe: "ferver brando 2–3 min · provar" },
      { col: 5, de: 0, ate: 12, titulo: "cobrir as sardinhas", detalhe: "morno · o mais submerso possível" },
      { col: 6, de: 0, ate: 13, titulo: "amornar e gelar", detalhe: "mín. 4 h · vira a partir de ~12 h" },
    ],
    modo: [
      { t: "Seque bem as sardinhas com papel-toalha e tempere com sal e pimenta dos dois lados." },
      { t: "Se quiser, passe leve na farinha e sacuda o excesso. Frite no azeite bem quente, em levas sem lotar a panela, 1 a 2 minutos por lado, só até dourar de leve. Retire para um refratário de vidro ou cerâmica.", timer: 180 },
      { t: "No mesmo azeite, em fogo médio-baixo, refogue a cebola, a cenoura, o alho, o louro e a pimenta em grão até a cebola ficar macia e translúcida — sem dourar muito." },
      { t: "Junte o vinagre, o vinho, a água e o açúcar. Ferva brando 2 a 3 minutos, só para tirar o ardido cru do vinagre. Prove e equilibre acidez e sal.", timer: 150 },
      { t: "Despeje o escabeche morno sobre as sardinhas, deixando-as o mais cobertas possível pelo líquido e pela cebola." },
      { t: "Deixe amornar 20 a 30 minutos na bancada — não horas —, tampe e leve à geladeira. Descansa no mínimo 4 horas; vira a partir de umas 12.", timer: 1500 },
    ],
    notas: [
      "Come frio ou em temperatura ambiente, sem reaquecer, com pão. Aguenta 4 a 5 dias na geladeira e melhora no dia seguinte.",
      "Para presente: fritar no fim da tarde e entregar na manhã seguinte dá 14 a 16 h de cura, a melhor janela.",
      "Azeite, não banha: a banha solidifica e embranquece na geladeira.",
      "Nunca alumínio ou ferro — o vinagre reage com metal e deixa gosto metálico.",
      "As espinhas finas amolecem no ácido em cerca de um dia e ficam comestíveis.",
      "Com vinagre de arroz, mais suave e adocicado, pode tirar o açúcar.",
    ],
  },
  {
    id: "molho-pimenta",
    capitulo: "conservas",
    titulo: "Molho de pimenta lacto-fermentado",
    kicker: "DEDO-DE-MOÇA + MALAGUETA · CALIBRADO NO MÉDIO",
    subtitulo: "Estilo Tabasco brasileiro: base frutada, malagueta como único calor. Rende 450–550 ml.",
    porcoes: 500, porcoesOpcoes: [500, 1000], ativo: 40, total: 10080,
    utensilio: "Pote ou garrafa de vidro limpo",
    faixa: "SAL A 3% DO PESO DE PIMENTA + ÁGUA · TUDO SUBMERSO",
    ingredientes: [
      { q: 346, u: "g", nome: "pimenta dedo-de-moça", obs: "fresca, já limpa" },
      { q: 40, u: "g", nome: "pimenta malagueta", obs: "o botão de volume — calibre provando" },
      { q: 5, u: "dentes", alt: { q: 25, u: "g" }, nome: "alho" },
      { q: 380, u: "ml", nome: "água filtrada", obs: "o suficiente para submergir" },
      { q: 23, u: "g", nome: "sal", obs: "3% do peso de pimenta + água" },
      { q: 45, u: "ml", nome: "vinagre de arroz ou de maçã", obs: "só no fim, a gosto" },
    ],
    grade: [
      { col: 1, de: 0, ate: 2, titulo: "picar grosso, na faca", detalhe: "sem cabinhos · com sementes · use luva" },
      { col: 2, de: 0, ate: 2, titulo: "provar o blend cru", detalhe: "calibrar o calor com mais malagueta" },
      { col: 3, de: 0, ate: 3, titulo: "cobrir com água", detalhe: "no pote limpo" },
      { col: 4, de: 0, ate: 4, titulo: "pesar e salgar a 3%", detalhe: "do peso de pimenta + água" },
      { col: 5, de: 0, ate: 4, titulo: "submergir, tampa frouxa", detalhe: "ambiente, longe do sol, num pratinho" },
      { col: 6, de: 0, ate: 4, titulo: "fermentar", detalhe: "1 semana a alguns meses · provar do 5º dia" },
      { col: 7, de: 0, ate: 5, titulo: "bater e engarrafar", detalhe: "acertar com vinagre · geladeira" },
    ],
    modo: [
      { t: "Tire os cabinhos e pique grosso na faca, em rodelas. Nada de processador agora — purê vira outro método, sem água. Mantenha as sementes para o médio. Use luva com a malagueta, lave bem as mãos e não esfregue os olhos." },
      { t: "Monte num pote ou garrafa bem limpo: dedo-de-moça, alho e a porção inicial de malagueta." },
      { t: "Prove o blend cru e ajuste o calor com mais malagueta se quiser. Dá para subir, não para descer — e fermentar não tira ardência, só arredonda." },
      { t: "Cubra com água até submergir. Pese o conjunto — pimenta mais água — e adicione 3% em sal. Dissolva bem." },
      { t: "Mantenha tudo submerso: um saquinho limpo com salmoura a 3% dentro (não água pura) enfiado no gargalo faz peso e isola do ar. Nenhuma pimenta acima da linha do líquido — é ali que mofa." },
      { t: "Tampa frouxa: a fermentação solta CO₂ e garrafa cheia transborda nos primeiros dias. Temperatura ambiente, longe do sol, num pratinho para aparar. Vai turvar e borbulhar — é o certo." },
      { t: "Fermente de uma semana a alguns meses. Comece a provar do quinto ao sétimo dia; o ponto é o gosto." },
      { t: "Para finalizar: escorra reservando a salmoura, bata as pimentas e o alho com um pouco dela, acerte com vinagre, engarrafe em vidro limpo e guarde na geladeira." },
    ],
    notas: [
      "Para escalar: malagueta a ~10% do peso da dedo-de-moça dá o médio; sal sempre 3% do peso de pimenta + água.",
      "Kahm (película branca lisa) é levedura inofensiva, retire com a colher. Mofo — qualquer coisa felpuda, de qualquer cor — descarta o lote inteiro.",
      "Pimenta de cheiro não substitui biquinho: é da família do habanero e pode arder absurdamente. Para perfume sem fogo, use biquinho.",
      "Garrafa de gargalo estreito é o formato mais chato para manter submerso.",
    ],
  },

  /* ===================== BEBER ===================== */
  {
    id: "quentao-mel",
    capitulo: "beber",
    titulo: "Quentão com mel",
    kicker: "SEM AÇÚCAR · O MEL ENTRA DISSOLVIDO NO FIM",
    subtitulo: "Mel não caramela: queima rápido e vira acre. O custo da troca é só a cor.",
    porcoes: 6, porcoesOpcoes: [6, 12], ativo: 10, total: 30,
    utensilio: "Panela",
    faixa: "NADA DE CARAMELIZAR O MEL",
    ingredientes: [
      { q: 750, u: "ml", nome: "água" },
      { q: 80, u: "g", nome: "gengibre fresco", obs: "em fatias" },
      { q: 3, u: "paus", alt: { q: 9, u: "g" }, nome: "canela" },
      { q: 8, u: "un", alt: { q: 2, u: "g" }, nome: "cravos-da-índia" },
      { q: 1, u: "un", alt: { q: 20, u: "g" }, nome: "casca de laranja" },
      { q: 500, u: "ml", nome: "cachaça" },
      { q: 120, u: "g", nome: "mel", obs: "ponto de partida — acerta provando" },
    ],
    grade: [
      { col: 1, de: 0, ate: 4, titulo: "infusão dos aromáticos", detalhe: "ferver e apurar 15 min em fogo baixo" },
      { col: 2, de: 0, ate: 5, titulo: "cachaça, fogo baixo", detalhe: "5 min mantém o teor · 15+ suaviza" },
      { col: 3, de: 0, ate: 6, titulo: "desligar e dissolver o mel", detalhe: "não ferver depois disso" },
      { col: 4, de: 0, ate: 6, titulo: "coar e servir", detalhe: "bem quente, nas canecas" },
    ],
    modo: [
      { t: "Panela com a água, o gengibre, a canela, o cravo e a casca de laranja. Ferva, abaixe e apure uns 15 minutos em fogo baixo, para extrair o sabor das especiarias e do gengibre.", timer: 900 },
      { t: "Acrescente a cachaça e mantenha em fogo baixo, sem ferver forte, para casar os sabores. Cinco minutos mantêm o teor alcoólico; quinze ou mais deixam bem mais suave.", timer: 300 },
      { t: "Desligue — ou deixe no mínimo — e dissolva o mel mexendo. Não ferva depois disso, para não perder o aroma. Prove e acerte o doce: mel é mais marcante que açúcar." },
      { t: "Coe e sirva bem quente, nas canecas." },
    ],
    notas: [
      "Mel é mais doce que açúcar: comece com 120 g e vá acertando no fim, nunca o contrário.",
      "Quer puxar o fundo tostado que o caramelo daria? Reforce o cravo e a canela.",
      "Maçã em pedaços junto com a laranja deixa mais frutado.",
    ],
  },
];
